#!/usr/bin/env python3

# This import must be first.
from fbmessengerlib import application

from fbmessengerlib import mqtt
from fbmessengerlib import windows
from fbmessengerlib import external
from fbmessengerlib import network

def main():
  application.init()
  network.init()
  mqtt.init()
  windows.init()
  external.init()

  application.main_loop()

if __name__ == "__main__":
  main()
